config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    # resourcesだといいね取り消しの時ルーティングエラーになる。idが付与されるため。
    # resourceだとidが付与されない。
    resource :favorites,      only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers"  => "relationships#followers",  as: "followers"
    get "search", to: "users#search"
  end

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 # dependent: :destroyは、１のモデルが消えた時にそれと付随してNのモデルも消す処理をするため。
  # 例）ユーザーが退会した時に、そのユーザーの投稿やいいねも一緒に消えるようにする処理
  has_many :books,         dependent: :destroy
  has_many :favorites,     dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # フォローした、されたの関係
  # relationshipsとreverse_of_relationshipsはアソシエーション（例：どれが誰の投稿なのかを関連づけるもの）がつながっているテーブル名
  # class_nameは実際のモデル名前
  # foreign_keyは外部キー（「ここの入れる値は、こっちから選んでいれなさい」な制約（がついている項目））としてなにを持つかを表している
  has_many :relationships,            class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  # has_many :yyy(テーブル名), through: :xxx(中間テーブル), source: :zzzで、テーブル同士が中間テーブルを通じてつながっていることを表現します。(followerテーブルとfollowedテーブルのつながりを表す)
  # 例）yyyにfollowedを入れると、followedテーブルから中間テーブルを通ってfollowerテーブルにアクセスすることができなくなる。
  # これを防ぐためにyyyには架空のテーブル名を、zzzは実際にデータを取得しにくいテーブル名を書く。
  has_many :followings, through: :relationships,            source: :followed
  has_many :followers,  through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length:{maximum: 50}



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # フォローした時の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外す時の処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)  # contentは検索ワード
    # 完全一致
    if method == "perfect"
      User.where(name: content)
    # 前方一致
    elsif method == "forward"
      # モデル名.where("カラム名 LIKE ?", 検索したい文字列 + "%")
      User.where("name LIKE ?", content + "%")
    # 後方一致
    elsif method == "backward"
      # モデル名.where("カラム名 LIKE ?", "%" + 検索したい文字列)
      User.where("name LIKE ?", "%" + content)
    # 部分一致
    else
      # モデル名.where("カラム名 LIKE ?", "%" + 検索したい文字列 + "%")
      User.where("name LIKE ?", "%" + content + "%")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_correct_user, only: [:edit,:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

    # 今日の投稿数
    @today_book = @books.created_today
    # 昨日の投稿数
    @yesterday_book = @books.created_yesterday
    # 今週の投稿数
    @this_week_book = @books.created_this_week
    # 先週の投稿数
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  # 指定した日の記録（投稿数）
  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      created_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{created_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% unless current_user == user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/_search.html.erb
<h2>検索結果</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
<!-- $("セレクタ")の部分はどこを変えるかという記述 -->
<!-- .html();の部分は、どう変えるかを指定している -->
<!-- .html()で先ほど指定した部分の中身を変えることを宣言している -->
<!-- j()は部分テンプレートをjsファイルに読み込む際に使うもの -->
$("#search_result").html("<%= j(render "search", search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <h2>投稿数の前日比・前週比</h2>

      <!-- 投稿数の前日比 -->
      <div class="table_width">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今日の投稿数</th>
              <th>昨日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @today_book.count %></td>
              <td><%= @yesterday_book.count %></td>
              <% if @yesterday_book.count == 0 %>
                <td>前日の投稿はありません</td>
              <% else %>
                <td>
                  <!-- to_f メソッドは、小数点までの数値を表示してくれる -->
                  <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
                  <%= (@the_day_before * 100).round %>%
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- 投稿数の前週日 -->
      <div class="table_width">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今週の投稿数</th>
              <th>先週の投稿数</th>
              <th>前週比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @this_week_book.count %></td>
              <td><%= @last_week_book.count %></td>
              <% if @last_week_book.count == 0 %>
                <td>先週の投稿はありません</td>
              <% else %>
                <td>
                  <!-- to_f メソッドは、小数点までの数値を表示してくれる -->
                  <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
                  <%= (@the_week_before * 100).round %>%
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>

      <h2>７日分の投稿数</h2>

      <!-- 過去７日分の投稿の一覧 -->
      <div class="table_width">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>６日前</th>
              <th>５日前</th>
              <th>４日前</th>
              <th>３日前</th>
              <th>２日前</th>
              <th>昨日</th>
              <th>今日</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @books.created_6days.count %></td>
              <td><%= @books.created_5days.count %></td>
              <td><%= @books.created_4days.count %></td>
              <td><%= @books.created_3days.count %></td>
              <td><%= @books.created_2days.count %></td>
              <td><%= @yesterday_book.count %></td>
              <td><%= @today_book.count %></td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- グラフ -->
      <canvas id="myLineChart"></canvas>
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
          $(document).on('turbolinks:load', function() {
            var ctx = document.getElementById("myLineChart");
            var myLineChart = new Chart(ctx, {
              // グラフの種類
              type: 'line',
              // グラフに描画するデータ
              data: {
                labels: ['６日前', '５日前', '４日前', '３日前', '２日前', '１日前', '今日'],
                datasets: [
                  {
                    // グラフに名前をつける
                    label: '投稿した本の数',
                    // データの値
                    data: [<%= @books.created_6days.count %>,
                           <%= @books.created_5days.count %>,
                           <%= @books.created_4days.count %>,
                           <%= @books.created_3days.count %>,
                           <%= @books.created_2days.count %>,
                           <%= @yesterday_book.count %>,
                           <%= @today_book.count %>
                    ],
                    // 線の色
                    borderColor: "rgba(0,0,255,1)",
                    // 線の下の塗りつぶしの色
                    backgroundColor: "rgba(0,0,0,0)"
                  }
                ],
              },
              options: {
                // グラフのタイトル
                title: {
                  // タイトル表示の許可するかどうか
                  display: true,
                  // タイトル名
                  text: '７日間の投稿数の比較'
                },
                scales: {
                  // y軸
                  yAxes: [{
                    // 目盛線
                    ticks: {
                      // 軸の最大値
                      suggestedMax: 10,
                      // 軸の最小値
                      suggestedMin: 0,
                      // 軸の刻み幅
                      stepSize: 1,
                      // 軸のラベル
                      callback: function(value, index, values){
                        return value
                      }
                    }
                  }]
                },
              }
            });
          });
        </script>

      <!-- 指定した日の記録（投稿数）-->
      <!-- 非同期通信は remote: true か local: false で設定 -->
      <%= form_with url: user_search_path(@user), method: :get, remote: true do |f| %>
        <%= f.date_field :created_at %>  <!-- 年/月/日 が表示される -->
        <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render "search", search_book: @search_book %>
        <% end %>
      </div>
    </div>
  </div>
</div>